version: "3.4"
services:
    mvc:
        build:
            context: .
            dockerfile: Dockerfile	
        ports:
          - "5000:80"
        depends_on:
          - mssql
    mssql:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
          - "2433:1433"
        environment:
            MSSQL_SA_PASSWORD: "Test1234" 
            ACCEPT_EULA: "Y"

